### ISSUE TITLE
是否能通过html5 api获取二进制数据推送

### ISSUE THREAD

**Issue by icode** [chxj1992/rtmp-js-streamer#2]
通过Audio API获取到音频数据，通过flash推送到服务器，是否可以？我查了下没找到js flash接口交互可以直接交互unit8 byte array，不知道是否支持？

**Comment by chxj1992** [comment]
其实并不是太了解Flash相关的东西，SO上看到一条提到用base64把 byte array 编码后再传递，不知道是否适用，以下是链接，希望有帮助
http://stackoverflow.com/questions/7340901/flash-passing-audio-data-bytearray-to-javascript

**Comment by icode** [comment]
base64 那就消耗太多了，我自己试试吧
